### Get all users
GET http://localhost:3000/users
Authorization: Bearer TOKEN

### Create a user (sign up)
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Admin",
    "password": "password"
}

### Login user (sign in)
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "Admin",
    "password": "password"
}
