### Get logged in user
GET http://localhost:4000/user
Authorization: Bearer ACCESS_TOKEN

### Refresh access token with refreh token
POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "REFRESH_TOKEN"
}

### Create a user (sign up)
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Admin",
    "password": "password"
}

### Login user (sign in)
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Admin",
    "password": "password"
}

### Logout user by deleting refresh token
DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "REFRESH_TOKEN"
}
